#!/usr/bin/env python
import sys
import os

histsize = 10000
HISTFILE = ".directory_history"
home = os.environ['HOME']


def remove_duplicates(commands):
    cmds = []
    for cmd in reversed(commands):
        if cmd not in cmds:
            cmds.append(cmd)
    return [cmd for cmd in reversed(cmds)]


def get_commands(directory):
    commands = []
    try:
        with open(home + "/" + HISTFILE, "r") as f:
            continued = False
            for line in f.readlines():
                line = line.strip()
                if not continued and not line.endswith('\\'):
                    try:
                        cmd_dir, command = line.split(";", 1)
                    except ValueError:
                        continue
                elif continued and line.endswith('\\'):
                    command += line[:-1] + '\\n'
                    continue
                elif continued:
                    command += line
                    continued = False
                else:  # line ends with backslash
                    try:
                        cmd_dir, command = line.split(";", 1)
                        command = command[:-1] + '\\n'
                        continued = True
                        continue
                    except ValueError:
                        continued = False
                        continue

                if cmd_dir == directory and len(commands) < histsize:
                    commands.append(command)
    except IOError:
        open(home + "/" + HISTFILE, 'a').close()

    commands = remove_duplicates(commands)

    return "\n".join(commands)

if __name__ == '__main__':
    try:
        print get_commands(sys.argv[1])
    except IndexError:
        print get_commands(os.getcwd())
