errfid = fopen('.matlaberror', 'w');
if numel(ME1.stack) > 0
    fprintf(errfid, '%s(%d): %s - %s\n', ...
        ME1.stack(end).file, ...
        ME1.stack(end).line, ...
        ME1.stack(end).name, ...
        ME1.message);
    for erridx = length(ME1.stack)-1:-1:1
        fprintf(errfid, '%s(%d): %s\n', ...
            ME1.stack(erridx).file, ...
            ME1.stack(erridx).line, ...
            ME1.stack(erridx).name);
    end
else
    fprintf(errfid, '%s', strrep(ME1.message, sprintf('\n'), ' - '));
end
fclose(errfid);
rethrow(ME1)
