#!/usr/bin/env zsh
lines=("${(@f):-$(tmux capture-pane -p -J -S -100)}")
for line in ${(Oa)lines}; do
  if [[ $line =~ '^> (/.*\([0-9]+\))| at (/.*:[0-9]+)' ]]; then
    findvim $match
    break
  fi
done
