#!/bin/zsh
fname=""
fnamefile=/cygdrive/c/temp/tempfname
if [ -e $fnamefile ]; then
    sed -i 's/^"\|[" \t]*$//g' $fnamefile
    fname=`cat $fnamefile`
    rm $fnamefile
    fname=$(cygpath -u "$fname")
fi
source $HOME/.zshrc
if [ "$fname" = "ECHO is on." -o "$fname" = "" ]; then
    ps cax | fgrep `which gvim` >& /dev/null
    if [ ! $? -eq 0 ]; then
        gvim &
    fi
else
    gvim --remote-tab-silent "$fname" &
fi
