# generic packages
before_install:
  - sudo apt-get update
  - sudo apt-get install -y git-core expect gawk
  - sudo apt-get install -y python-software-properties software-properties-common

# install Tmux 2.5
install:
  - VERSION=2.5
  - sudo apt-get -y remove tmux
  - sudo apt-get -y install wget tar libevent-dev libncurses-dev make
  - wget https://github.com/tmux/tmux/releases/download/${VERSION}/tmux-${VERSION}.tar.gz
  - tar xf tmux-${VERSION}.tar.gz
  - rm -f tmux-${VERSION}.tar.gz
  - cd tmux-${VERSION}
  - ./configure
  - make
  - sudo make install
  - cd -
  - sudo rm -rf /usr/local/src/tmux-*
  - sudo mv tmux-${VERSION} /usr/local/src

# override PS1 and irb prompt, fetch a git repo used for testing
before_script:
  - echo 'export PS1="\$ "' >> ~/.bashrc
  - echo 'IRB.conf[:PROMPT_MODE] = :SIMPLE' >> ~/.irbrc
  - git clone https://github.com/tmux-plugins/tmux-example-plugin ~/tmux-example-plugin

script: ./test/run-tests-within-vm
